### ISSUE TITLE
Hide network components on nav When the page does not contain Ethereum content

### ISSUE THREAD

**Issue by 0xferit** [proveuswrong/webapp-tp#180]
Example pages:
- FAQ
- About 

Things to track for this logic:
- chainId
- metamaskChainId
- isProviderDetected

Problem: once chainId is set, it needs to be reset to make the logic work. However getGraphMetadata is doing longpolling. Needs a bit of refactor.

Expected behavior: visit FAQ directly.

To reproduce the bug: visit frontpage then navigate to FAQ. You will see that network components are displayed in the navigation bar.

**Comment by gratestas** [comment]
@0xferit , there is a simple solution to address this issue. Since the intended functionality also overlaps with Router, we can check whether the dynamic params from the current URL match `:chain` segment:
```
const params = useParams();
...
 {params.chain && <ButtonConnect />}
 {params.chain && <ButtonSelectNetwork />}
 ...
 ```
 But ofc, we should also consider whether this approach is sufficient for the long term.
